CREATE TABLE IF NOT EXISTS PRODUCTS (
   ID UUID CONSTRAINT PK_PRODUCTS PRIMARY KEY,
   SKU VARCHAR(32) NOT NULL,
   TITLE VARCHAR(160) NOT NULL,
   REDUCEDTITLE VARCHAR(60),
   DESCRIPTION VARCHAR(255),
   PRICE DECIMAL(21,2) DEFAULT 0 NOT NULL,
   SEARCHTEXT TEXT GENERATED ALWAYS AS (
      LOWER(SKU || TITLE || REDUCEDTITLE)
   ) STORED
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_PRODUCTS_SKU ON PRODUCTS (SKU);

CREATE EXTENSION PG_TRGM;
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_PRODUCTS_SEARCHTEXT ON PRODUCTS USING GIST (SEARCHTEXT GIST_TRGM_OPS(SIGLEN=64));